apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/source/Dockerfile
      - name: baseWorkspace
        description: The path to the base source workspace
        default: /workspace/source
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default:  /workspace/source
  outputs:
    resources:
      - name: base-image
        type: image
      - name: go-image
        type: image
      - name: go-maven-image
        type: image
      - name: gradle-image
        type: image
      - name: maven-image
        type: image
      - name: nodejs-image
        type: image
  steps:
    - name: next-release-version
      image: rawlingsj/jx:dev136
      command:
        - jx
      args:
        - step
        - next-version
        - -t
        - --use-git-tag-only
      resources:
        limits:
          cpu: 0.2
          memory: 256Mi
        requests:
          cpu: 0.1
          memory: 128Mi
      env:
      - name: GIT_COMMITTER_EMAIL
        value: jenkins-x@googlegroups.com
      - name: GIT_AUTHOR_EMAIL
        value: jenkins-x@googlegroups.com
      - name: GIT_AUTHOR_NAME
        value: jenkins-x-bot
      - name: GIT_COMMITTER_NAME
        value: jenkins-x-bot
      workingDir: ${inputs.params.baseWorkspace}
    - name: replace-versions
      image: centos:7
      command:
        - ./replace-versions.sh
      resources:
        limits:
          cpu: 0.2
          memory: 256Mi
        requests:
          cpu: 0.1
          memory: 128Mi
      workingDir: ${inputs.params.baseWorkspace}
    - name: build-and-push-base
      image: rawlingsj/executor:dev21
      command:
        - /bin/bash
      args: ['-c','/kaniko/executor --dockerfile=/workspace/source/Dockerfile.base --destination=docker.io/rawlingsj/jenkins-base:$(cat /workspace/source/VERSION) --context=/workspace/source/jenkins-base --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/ --cache=true --cache-dir=/workspace --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000']
      resources:
        limits:
          cpu: 1
          memory: 2048Mi
        requests:
          cpu: 0.5
          memory: 1024Mi
    - name: warm-cache
      image: gcr.io/kaniko-project/warmer
      args:
        - --cache-dir=/workspace
        - --image=docker.io/rawlingsj/jenkins-base
      resources:
        limits:
          cpu: 1
          memory: 2048Mi
        requests:
          cpu: 0.5
          memory: 1024Mi
    - name: build-and-push-maven
      image: rawlingsj/executor:dev21
      command:
        - /bin/bash
      args: ['-c','/kaniko/executor --dockerfile=/workspace/source/Dockerfile.maven --destination=docker.io/rawlingsj/jenkins-maven:$(cat /workspace/source/VERSION) --context=/workspace/source/jenkins-maven --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/ --cache=true --cache-dir=/workspace --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000']
      resources:
        limits:
          cpu: 1
          memory: 2048Mi
        requests:
          cpu: 0.5
          memory: 1024Mi